### PR TITLE
fix: changed default ES instance type for DEV stage

### PR DESCRIPTION
**Pull request by damiandmn**
Issue #, if available:

Description of changes:

Checklist:

* [x] Have you successfully deployed to an AWS account with your changes?
* [x] Have you written new tests for your core changes, as applicable?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by damiandmn** [comment]
I think that the elasticsearch m3.large instance for the dev environment is too large and increases the stack costs.
I consider that a t3.medium would be enough taking into consideration the other resources for dev.

**Comment by carvantes** [comment]
Hi, 
thanks for submitting this PR. A t3.medium instance is 50% cheaper and probably good enough for most dev use cases. We'll run our integration tests using t3.medium before merging to ensure that it is sufficient for a typical dev workflow(It most likely is)

**Review by carvantes — APPROVED** [review]

**Comment by carvantes** [comment]
Integration tests ran smoothly on t3.medium. Also verified that changing the ES instance type causes no interruption(i.e. customers who already have a dev stack and update it with these changes won't have any issues)

Looks good. I'll merge this now. Thanks for the contribution @damiandmn !

**Comment by damiandmn** [comment]
Awesome! Thank you!

**Pull request merged**
