### PR TITLE
chore: Add @types/cors to dev dependency

### PR DESCRIPTION
**Pull request by nguyen102**
Issue #, if available:

Description of changes:
This resolves a warning when running `sls deploy`
```
/Volumes/unix/workplace/fhir-works-on-aws-deployment/node_modules/fhir-works-on-aws-routing/lib/app.d.ts (2,29): Could not find a declaration file for module 'cors'. '/Volumes/unix/workplace/fhir-works-on-aws-deployment/node_modules/cors/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cors` if it exists or add a new declaration (.d.ts) file containing `declare module 'cors';`
```

Checklist:

* [x] Have you successfully deployed to an AWS account with your changes?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by carvantes — APPROVED** [review]
The fact that this bug is on mainline means that our gh actions are not set up properly. They are not doing a proper yarn run release. Can you fix that?

**Review by carvantes — CHANGES_REQUESTED** [review]
nvm my previous approval. This doesn't look right.

This package does not depend on cors directly. The routing package is the one that needs to include the cors types

**Comment by rsmayda** [comment]
> nvm my previous approval. This doesn't look right.
> 
> This package does not depend on cors directly. The routing package is the one that needs to include the cors types

It looks like routing does - https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/package.json#L45

This may actually be an sls issue/concern on how they bundle it up?

Looking at app.ts it looks like this is a param that the deployment package must pass in: https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/app.ts#L30

@nguyen102 Are you getting this error when running `yarn run release` or just when you are running `sls deploy`?

**Comment by carvantes** [comment]
> > nvm my previous approval. This doesn't look right.
> > This package does not depend on cors directly. The routing package is the one that needs to include the cors types
> 
> It looks like routing does - https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/package.json#L45
> 
> This may actually be an sls issue/concern on how they bundle it up?
> 
> Looking at app.ts it looks like this is a param that the deployment package must pass in: https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/app.ts#L30
> 
> @nguyen102 Are you getting this error when running `yarn run release` or just when you are running `sls deploy`?

The routing package declares it on `devDependencies` but it should declare it in `dependencies`. This is because it is using the cors types as part of its own exported type declarations (the type of the function param you mentioned)

**Comment by rsmayda** [comment]
@carvantes Thanks for the explainer and it makes sense -- closing this PR in favor of the routing one: https://github.com/awslabs/fhir-works-on-aws-routing/pull/43

**Pull request closed without merging**
